name: expense_tracker
description: "A daily expense tracker app."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^17.0.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.4
  uuid: ^4.5.2
  cupertino_icons: ^1.0.8
  currency_converter: ^2.0.0

dev_dependencies:
  build_runner: ^2.10.4
  json_serializable: ^6.11.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: CurrencySymbols
      fonts:
        - asset: assets/fonts/currency-symbols-v1Regular.ttf
